"""Markdown research reports rendered to PDF.

Replaces the earlier @react-pdf/renderer implementation. Route is
markdown -> HTML -> fpdf2.write_html, which gives headings, lists, links,
tables, code and blockquotes without hand-mapping every token type.

DejaVu is bundled in fonts/ rather than using fpdf2's built-in faces: the
built-ins are Latin-1 only and would raise on the accented names, curly quotes
and em dashes a research report routinely contains.
"""

from __future__ import annotations

import datetime as _dt
from pathlib import Path

import markdown as _markdown
from fpdf import FPDF
from fpdf.enums import XPos, YPos
from fpdf.fonts import FontFace

FONT_DIR = Path(__file__).parent / "fonts"

BODY = "DejaVuSerif"
HEAD = "DejaVuSans"
MONO = "DejaVuSansMono"

INK = (26, 26, 26)
MUTED = (120, 120, 120)
RULE = (224, 224, 224)


class Report(FPDF):
    def __init__(self, title: str):
        super().__init__(orientation="P", unit="pt", format="A4")
        self.doc_title = title
        self.set_auto_page_break(auto=True, margin=64)
        self.set_margins(56, 56, 56)

        for family, stem in ((BODY, "DejaVuSerif"), (HEAD, "DejaVuSans"), (MONO, "DejaVuSansMono")):
            self.add_font(family, "", FONT_DIR / f"{stem}.ttf")
        self.add_font(BODY, "B", FONT_DIR / "DejaVuSerif-Bold.ttf")
        self.add_font(HEAD, "B", FONT_DIR / "DejaVuSans-Bold.ttf")
        # Italic is not bundled; map it to the regular face so <i> degrades
        # gracefully instead of raising.
        self.add_font(BODY, "I", FONT_DIR / "DejaVuSerif.ttf")
        self.add_font(BODY, "BI", FONT_DIR / "DejaVuSerif-Bold.ttf")

    def footer(self) -> None:
        self.set_y(-42)
        self.set_font(HEAD, "", 8)
        self.set_text_color(*MUTED)
        self.cell(0, 10, "MicroManus research report", align="L")
        self.set_x(-100)
        self.cell(60, 10, f"{self.page_no()} / {{nb}}", align="R")


def _masthead(pdf: Report, title: str) -> None:
    pdf.set_font(HEAD, "B", 22)
    pdf.set_text_color(17, 17, 17)
    # align="L" matters: multi_cell justifies by default, which stretches the
    # word spacing on a wrapped title.
    pdf.multi_cell(0, 26, title, align="L", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    today = _dt.date.today()
    generated = f"{today.strftime('%B')} {today.day}, {today.year}"
    pdf.set_font(HEAD, "", 9)
    pdf.set_text_color(*MUTED)
    pdf.cell(0, 16, f"Generated by MicroManus · {generated}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.ln(6)
    pdf.set_draw_color(*RULE)
    y = pdf.get_y()
    pdf.line(pdf.l_margin, y, pdf.w - pdf.r_margin, y)
    pdf.ln(14)


def render_report(title: str, body_markdown: str) -> bytes:
    """Renders a markdown report and returns PDF bytes."""
    pdf = Report(title)
    pdf.alias_nb_pages()
    pdf.add_page()
    _masthead(pdf, title)

    html = _markdown.markdown(
        body_markdown or "",
        extensions=["tables", "fenced_code", "sane_lists", "nl2br"],
    )

    pdf.set_font(BODY, "", 11)
    pdf.set_text_color(*INK)
    pdf.write_html(
        html,
        tag_styles={
            "h1": FontFace(family=HEAD, emphasis="BOLD", size_pt=16, color=(17, 17, 17)),
            "h2": FontFace(family=HEAD, emphasis="BOLD", size_pt=13, color=(34, 34, 34)),
            "h3": FontFace(family=HEAD, emphasis="BOLD", size_pt=11, color=(51, 51, 51)),
            "h4": FontFace(family=HEAD, emphasis="BOLD", size_pt=10, color=(51, 51, 51)),
            "a": FontFace(color=(26, 95, 180)),
            "blockquote": FontFace(family=BODY, color=(85, 85, 85)),
            "code": FontFace(family=MONO, size_pt=9),
            "pre": FontFace(family=MONO, size_pt=9),
        },
        li_prefix_color=(120, 120, 120),
    )

    return bytes(pdf.output())
